<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Update Guest Registration</title>
<link rel="stylesheet" type="text/css" href="view.css" media="all">
<script type="text/javascript" src="view.js"></script>

</head>
<body id="main_body" >
	
	<img id="top" src="top.png" alt="">
	<div id="form_container">
	
		<h1><a>Update Guest Registration</a></h1>
		<form id="form_589332" class="appnitro"  method="post" action="">
					<div class="form_description">
			<h2>Update Guest Registration</h2>
			<p></p>
		</div>						
			<ul >
					<li id="li_4" >
		<label class="description" for="GuestID">Guest ID </label>
		<div>
			<input id="element_4" name="GuestID" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>			<li id="li_1" >
		<label class="description" for="GuestName">Guest Name </label>
		<div>
			<input id="element_1" name="GuestName" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_2" >
		<label class="description" for="GuestAddress">Guest Address </label>
		<div>
			<textarea id="element_2" name="GuestAddress" class="element textarea medium"></textarea> 
		</div> 
		</li>		<li id="li_3" >
		<label class="description" for="GuestAffiliation">Guest Affiliation </label>
		<div>
			<input id="element_3" name="GuestAffiliation" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>
			
					<li class="buttons">
			    <input type="hidden" name="form_id" value="589332" />
			    
				<input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
		</li>
			</ul>
		</form>	
		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>
	<img id="bottom" src="bottom.png" alt="">
	</body>
</html>