<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Register New Booking</title>
<link rel="stylesheet" type="text/css" href="view.css" media="all">
<script type="text/javascript" src="view.js"></script>
<script type="text/javascript" src="calendar.js"></script>
</head>
<body id="main_body" >
	
	<img id="top" src="top.png" alt="">
	<div id="form_container">
	
		<h1><a>Register New Booking</a></h1>
		<form id="form_591534" class="appnitro"  method="post" action="">
					<div class="form_description">
			<h2>Register New Booking</h2>
		</div>						
			<ul >
			
					<li id="li_1" >
		<label class="description" for="hotelID">Hotel ID </label>
		<div>
			<input id="element_1" name="hotelID" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_2" >
		<label class="description" for="roomNumber">Room Number </label>
		<div>
			<input id="element_2" name="roomNumber" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_3" >
		<label class="description" for="guestID">Guest ID </label>
		<div>
			<input id="element_3" name="guestID" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		
		<li id="li_4" >
		<label class="description" for="startDate">Start Date (yyyy-mm-dd) </label>
		<div>
			<input id="element_4" name="startDate" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		
		<li id="li_5" >
		<label class="description" for="endDate">End Date (yyyy-mm-dd) </label>
		<div>
			<input id="element_5" name="endDate" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>
			
					<li class="buttons">
			    <input type="hidden" name="form_id" value="591534" />
			    
				<input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
		</li>
			</ul>
		</form>	
		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>
	<img id="bottom" src="bottom.png" alt="">
	</body>
</html>