<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Register New Booking</title>
<link rel="stylesheet" type="text/css" href="view.css" media="all">
<script type="text/javascript" src="view.js"></script>
<script type="text/javascript" src="calendar.js"></script>
</head>
<body id="main_body" >
	
	<img id="top" src="top.png" alt="">
	<div id="form_container">
	
		<h1><a>Register New Booking</a></h1>
		<form id="form_591534" class="appnitro"  method="post" action="">
					<div class="form_description">
			<h2>Register New Booking</h2>
		</div>						
			<ul >
			
					<li id="li_1" >
		<label class="description" for="hotelID">Hotel ID </label>
		<div>
			<input id="element_1" name="hotelID" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_2" >
		<label class="description" for="roomNumber">Room Number </label>
		<div>
			<input id="element_2" name="roomNumber" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_3" >
		<label class="description" for="guestID">Guest ID </label>
		<div>
			<input id="element_3" name="guestID" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_4" >
		<label class="description" for="startDate">Start Date </label>
		<span>
			<input id="element_4_1" name="startDateMM" class="element text" size="2" maxlength="2" value="" type="text"> /
			<label for="startDateMM">MM</label>
		</span>
		<span>
			<input id="element_4_2" name="startDateDD" class="element text" size="2" maxlength="2" value="" type="text"> /
			<label for="startDateDD">DD</label>
		</span>
		<span>
	 		<input id="element_4_3" name="startDateYYYY" class="element text" size="4" maxlength="4" value="" type="text">
			<label for="startDateYYYY">YYYY</label>
		</span>
	
		<span id="calendar_4">
			<img id="cal_img_4" class="datepicker" src="calendar.gif" alt="Pick a date.">	
		</span>
		<script type="text/javascript">
			Calendar.setup({
			inputField	 : "element_4_3",
			baseField    : "element_4",
			displayArea  : "calendar_4",
			button		 : "cal_img_4",
			ifFormat	 : "%B %e, %Y",
			onSelect	 : selectDate
			});
		</script>
		 
		</li>		<li id="li_5" >
		<label class="description" for="element_5">End Date </label>
		<span>
			<input id="element_5_1" name="endDateMM" class="element text" size="2" maxlength="2" value="" type="text"> /
			<label for="endDateMM">MM</label>
		</span>
		<span>
			<input id="element_5_2" name="endDateDD" class="element text" size="2" maxlength="2" value="" type="text"> /
			<label for="endDateDD">DD</label>
		</span>
		<span>
	 		<input id="element_5_3" name="endDateYYYY" class="element text" size="4" maxlength="4" value="" type="text">
			<label for="endDateYYYY">YYYY</label>
		</span>
	
		<span id="calendar_5">
			<img id="cal_img_5" class="datepicker" src="calendar.gif" alt="Pick a date.">	
		</span>
		<script type="text/javascript">
			Calendar.setup({
			inputField	 : "element_5_3",
			baseField    : "element_5",
			displayArea  : "calendar_5",
			button		 : "cal_img_5",
			ifFormat	 : "%B %e, %Y",
			onSelect	 : selectDate
			});
		</script>
		 
		</li>
			
					<li class="buttons">
			    <input type="hidden" name="form_id" value="591534" />
			    
				<input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
		</li>
			</ul>
		</form>	
		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>
	<img id="bottom" src="bottom.png" alt="">
	</body>
</html>